language: cpp
os: osx
compiler: clang
env:
  global:
    - QT_DIR=/usr/local/opt/qt
    - PATH=$QT_DIR/bin:$PATH
    - HOMEBREW_NO_AUTO_UPDATE=1
install:
  - brew install qt opencv
script:
  - echo $PATH
  - qmake lipr.pro
  - ls -l /usr/local/opt
  - ls -l /usr/local/opt/opencv
  - ls -l /usr/local/opt/opencv/include
  - ls -l /usr/local/opt/opencv/include/opencv4
  - make
